services:
  mongo:
    image: mongo:7
    container_name: rust-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: rust-redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: /home/shvvkz/docker-volumes/mongo-data
      o: bind
